version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: your_db_username
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: